# Simplified GitHub Pages Deployment Workflow (Updated)
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy-updates

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Use existing out directory
        run: |
          echo "Using existing out directory if available"
          if [ -d "out" ]; then
            echo "Found existing out directory:"
            ls -la out/
          else
            echo "Creating minimal out directory"
            mkdir -p out
            cp -f index.html out/ || echo "<html><body><h1>Mac Wayne Official</h1></body></html>" > out/index.html
            cp -f CNAME out/ || echo "macwayneofficial.com" > out/CNAME
          fi
      
      - name: Copy static content to out directory
        run: |
          # Copy all HTML files from root
          cp -f *.html out/ || echo "No HTML files found in root"
          
          # Copy necessary assets
          [ -d "js" ] && cp -r js out/ || echo "No js directory"
          [ -d "css" ] && cp -r css out/ || echo "No css directory"
          [ -d "images" ] && cp -r images out/ || echo "No images directory"
          [ -d "styles" ] && cp -r styles out/ || echo "No styles directory"
          [ -d "public" ] && cp -r public out/ || echo "No public directory"
          
          # Copy CNAME file for custom domain
          [ -f "CNAME" ] && cp CNAME out/ || echo "No CNAME file found"
          
          # Ensure index.html exists
          if [ ! -f "out/index.html" ]; then
            if [ -f "index.html" ]; then
              cp index.html out/
            else
              echo "<html><body><h1>Mac Wayne Official</h1><p>Welcome to the official site</p></body></html>" > out/index.html
            fi
          fi
          
      - name: List files in out directory
        run: ls -la out/
        
      - name: Debug artifact upload
        run: |
          echo "Setting explicit permissions on out directory"
          chmod -R 755 out
          echo "Verifying out directory content before upload:"
          find out -type f | sort
          echo "Total files: $(find out -type f | wc -l)"
          echo "Directory size: $(du -sh out)"
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: out
          
      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifact
          path: out
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
